import './globals.css'
import {RecoilRootProvider} from "../lib/recoil/RecoilRootProvider";

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </head>
        <body>
        <RecoilRootProvider>
            {children}
        </RecoilRootProvider>
        </body>
        </html>
    )
}

